// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoAp34rE_o0nO-20H6OJa4jX1BjUTSgyc',
    appId: '1:445665968305:web:04465795f71d149ac3e290',
    messagingSenderId: '445665968305',
    projectId: 'chorechart-e8fe3',
    authDomain: 'chorechart-e8fe3.firebaseapp.com',
    storageBucket: 'chorechart-e8fe3.appspot.com',
    measurementId: 'G-V5NW06WPSM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLn0VWTRGpgrxtgAxCclBc65mknJ6VGhg',
    appId: '1:445665968305:android:3353a79e22734d4fc3e290',
    messagingSenderId: '445665968305',
    projectId: 'chorechart-e8fe3',
    storageBucket: 'chorechart-e8fe3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVYgCBIdQLIjA_H_NvmKuCrUX-Rl9n8d8',
    appId: '1:445665968305:ios:5baea05b987bc86fc3e290',
    messagingSenderId: '445665968305',
    projectId: 'chorechart-e8fe3',
    storageBucket: 'chorechart-e8fe3.appspot.com',
    iosClientId:
        '445665968305-mget9arcmkkeectep9eos7lmcshnbjmi.apps.googleusercontent.com',
    iosBundleId: 'com.creator.choreApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVYgCBIdQLIjA_H_NvmKuCrUX-Rl9n8d8',
    appId: '1:445665968305:ios:5baea05b987bc86fc3e290',
    messagingSenderId: '445665968305',
    projectId: 'chorechart-e8fe3',
    storageBucket: 'chorechart-e8fe3.appspot.com',
    iosClientId:
        '445665968305-mget9arcmkkeectep9eos7lmcshnbjmi.apps.googleusercontent.com',
    iosBundleId: 'com.creator.choreApp',
  );
}
